"""add strategy and RunResult

Revision ID: 01df5650683d
Revises: 37e14171cb68
Create Date: 2017-05-15 20:11:20.883467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01df5650683d'
down_revision = '37e14171cb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Date(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('last_time', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_result')
    op.drop_table('codes')
    # ### end Alembic commands ###
