"""change topic model

Revision ID: 03031080b2db
Revises: 01df5650683d
Create Date: 2017-05-16 11:00:09.286110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03031080b2db'
down_revision = '01df5650683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('topics', sa.Column('type', sa.Integer(), nullable=True))
    op.drop_constraint('topics_ibfk_1', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'category', ['type'], ['id'])
    op.drop_column('topics', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_ibfk_1', 'topics', 'groups', ['group_id'], ['id'])
    op.drop_column('topics', 'type')
    op.drop_table('category')
    # ### end Alembic commands ###
