"""change user model

Revision ID: b23646bfa308
Revises: b3a4d9afc884
Create Date: 2017-05-17 14:05:47.805597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23646bfa308'
down_revision = 'b3a4d9afc884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strategy_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strategy_num')
    # ### end Alembic commands ###
