"""change strategy model

Revision ID: b76a2f91975c
Revises: b23646bfa308
Create Date: 2017-05-18 14:34:40.551164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b76a2f91975c'
down_revision = 'b23646bfa308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('note', sa.Text(), nullable=True))
    op.drop_column('run_result', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_result', sa.Column('note', mysql.TEXT(), nullable=True))
    op.drop_column('codes', 'note')
    # ### end Alembic commands ###
