"""update user

Revision ID: e3803a8c272e
Revises: 94b8755fb6da
Create Date: 2017-04-30 11:44:55.784371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3803a8c272e'
down_revision = '94b8755fb6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_num', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('topic_num', sa.Integer(), nullable=False))
    op.drop_column('users', 'postNum')
    op.drop_column('users', 'topicNum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('topicNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('postNum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('users', 'topic_num')
    op.drop_column('users', 'post_num')
    # ### end Alembic commands ###
